### ISSUE TITLE
[Inconsistancy between encoding and decoding] TCAP_MAP.MAP_MS_DataTypes.CheckIMEI_Arg

### ISSUE THREAD

**Issue by p1-scg** [ANSSI-FR/pycrate#14]
Hello,

I dont know if I use encoding or decoding ASN1 object the right way.
I would like to encode and decode fields from CheckIMEI_Arg
- imei
- requestedEquipmentInfo

In below, you will find the script to reproduce the test case.
**Test case for decoding:**

from pycrate_asn1dir import TCAP_MAP
import binascii

test = TCAP_MAP.MAP_MS_DataTypes.CheckIMEI_Arg

pdu = "300e0408010000000000060003020780000000"
test.from_ber(binascii.unhexlify(pdu))

**Output:**
pycrate_asn1rt.err.ASN1ObjErr: CheckIMEI-Arg.requestedEquipmentInfo: value out of size constraint, (1, 1)
The value of requestedEquipmentInfo is (1, 1)
But the constraint size range between 2 and 8 for the bits length (second item of the tuple).

**Test case for encoding:**

test_1 = TCAP_MAP.MAP_MS_DataTypes.CheckIMEI_Arg
context={u'imei': '\x01\x00\x00\x00\x00\x00\x06\x00', u'requestedEquipmentInfo': (1, 1)}
test_1.set_val(context)

**Output:**
pycrate_asn1rt.err.ASN1ObjErr: CheckIMEI-Arg.requestedEquipmentInfo: value out of size constraint, (1, 1)

**According to documentation:**
for BIT STR object, the way to use set_val() method  (in pycrate_asn1rt/asnobj_str.py) is to used set of str (from the object's NamedBitList)

test_3 = TCAP_MAP.MAP_MS_DataTypes.CheckIMEI_Arg
context={u'imei': '\x01\x00\x00\x00\x00\x00\x06\x00', u'requestedEquipmentInfo': set([u'equipmentStatus'])}
test_3.set_val(context)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pycrate_asn1rt/asnobj.py", line 607, in set_val
    self._safechk_val(self._val)
  File "pycrate_asn1rt/asnobj_construct.py", line 566, in _safechk_val
    self._cont[k]._safechk_val(val[k])
  File "pycrate_asn1rt/asnobj_str.py", line 124, in _safechk_val
    raise(ASN1ObjErr('{0}: invalid value, {1!r}'.format(self.fullname(), val)))
pycrate_asn1rt.err.ASN1ObjErr: CheckIMEI-Arg.requestedEquipmentInfo: invalid value, set([u'equipmentStatus'])

How could I suppose to decode this hexadecimal pdu "300e0408010000000000060003020780000000" ?

And what is the way to encode the BIT STRING object ? with tuple object or set of str object ? which is the size contraint to set 2..8 bits ?

I think it has a problem concerning the contraint size interpretation in ASN1 doc:
RequestedEquipmentInfo::= BIT STRING {
equipmentStatus (0),
bmuef (1)} (SIZE (2..8))

Thank you.

**Comment by mitshell** [comment]
The response is twofolds:

1) The buffer provided seems effectively invalid according to the ASN.1 object TCAP_MAP.MAP_MS_DataTypes.CheckIMEI_Arg. You can see that by generating the binary structure during the decoding:

    >>> f = TCAP_MAP.MAP_MS_DataTypes.CheckIMEI_Arg
    >>> buf = unhexlify(b"300e0408010000000000060003020780000000")
    >>> f.from_ber_ws(buf)
    [...]
    >>> print(f._struct.show())
    ### CheckIMEI-Arg ###
     ### T ###
      <Class : 0 (UNIVERSAL)>
      <PC : 1 (constructed)>
      <Val : 16 (SEQUENCE, SEQUENCE OF)>
     ### L ###
      <Form : 0 (short)>
      <Val : 14>
     ### V ###
      ### imei ###
       ### T ###
        <Class : 0 (UNIVERSAL)>
        <PC : 0 (primitive)>
        <Val : 4 (OCTET STRING)>
       ### L ###
        <Form : 0 (short)>
        <Val : 8>
       <V : 0x0100000000000600>
      ### requestedEquipmentInfo ###
       ### T ###
        <Class : 0 (UNIVERSAL)>
        <PC : 0 (primitive)>
        <Val : 3 (BIT STRING)>
       ### L ###
        <Form : 0 (short)>
        <Val : 2>
       ### V ###
        <BU : 7>
        <BS : 0x80> 

You can see that the BU field from the V field of requestedEquipmentInfo says 7 bits of padding, hence a single bit of value in BS, what is out of the size constraint provided by the MAP specification.

It is possible to disable all size checking on ASN.1 objects like this:

    >>> from pycrate_asn1rt.asnobj import *
    >>> ASN1Obj._SAFE_BND = False

This way, the buffer will be decoded fine and you won't get any error. In the same way, you will be able to encode values out of any size constraints without error.

2) There is effectively what can be considered as a bug when setting a BitString value from a set of named bits. This generate the shorter bit string possible, without padding according to the potential size constraint, hence raising an error in your case.

    >>> f1 = f._cont['requestedEquipmentInfo']
    >>> f1.set_val({'requestedEquipmentInfo'})

This raises because it generates a BitString value of length 1.

    >>> f1.set_val({'bmuef'})
    >>> f1.set_val({'requestedEquipmentInfo', 'bmuef'})

Those are fine because they generate a BitString value of length 2. In order to set the requestedEquipmentInfo flag properly (yet), it is required to set it with a straight BitString value:

    >>> f1.set_val((0b10, 2))
    >>> f1.to_asn1()
    "'10'B -- equipmentStatus --"

A patch should be made here:
https://github.com/ANSSI-FR/pycrate/blob/ae1a34d5dc01345881a5380e0fc0d7cf0280129b/pycrate_asn1rt/asnobj_str.py#L158
to extend the 2nd part of the value (the bit length) to the lower bound of any potential size constraint.

I'll do this when I have time, contributions are welcome otherwise.

**Comment by mitshell** [comment]
This is fixing the bug: https://github.com/ANSSI-FR/pycrate/commit/c7e123d1fda1d7185ed437e1f4311c75a8c36d6e
thanks for the report

**Comment by p1-scg** [comment]
It works perfectly well, thank you.

**Comment by mitshell** [comment]
Fixed again in https://github.com/ANSSI-FR/pycrate/commit/a36cb17cbe3fdbd21e56cd0efa4fcc8dc8ab73bd
